# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='caption_review',
            field=models.CharField(default=None, max_length=240),
        ),
    ]
