# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_postmodel_caption_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='caption_review',
            field=models.CharField(max_length=240),
        ),
    ]
