# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170819_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='caption_review',
        ),
    ]
